### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Boolman** [claranet/rubrik-exporter#1]
I'm having trouble getting this to work on my rig. 

OS: ubuntu 16.04
go version go1.10 linux/amd64
rubrik version: 4.1.1-2229

```
/usr/local/bin/rubrik-exporter -listen-address ":9478" -log.level debug -rubrik.url https://10.0.0.70/ -rubrik.username prometheus -rubrik.password "#secret"
DEBU[0000] Create Rubrik Exporter instance               file=main.go line=37
DEBU[0000] Create new API Instance                       file=rubrik_api.go line=72
INFO[0000] Session-Token: %s                             file=rubrik_api.go line=81
DEBU[0000] Starting Server: :9478                        file=main.go line=49
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/stats/per_vm_storage  file=rubrik_api.go line=43
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/stats/per_vm_storage?  file=rubrik_api.go line=51
INFO[0010] Requested action: /api/internal/stats/per_vm_storage  file=rubrik_api.go line=43
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/stats/streams/count  file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/stats/streams/count?  file=rubrik_api.go line=51
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/stats/per_vm_storage?  file=rubrik_api.go line=51
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/stats/runway_remaining  file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/stats/runway_remaining?  file=rubrik_api.go line=51
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/archive/location  file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/archive/location?  file=rubrik_api.go line=51
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/v1/vmware/vm           file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/v1/vmware/vm?  file=rubrik_api.go line=51
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/stats/average_storage_growth_per_day  file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/stats/average_storage_growth_per_day?  file=rubrik_api.go line=51
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/nutanix/vm    file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/nutanix/vm?  file=rubrik_api.go line=51
DEBU[0010] Is logged in: true                            file=rubrik_api.go line=39
INFO[0010] Requested action: /api/internal/report        file=rubrik_api.go line=43
DEBU[0010] Request full URL: https://10.0.0.70//api/internal/report?report_template=ProtectionTasksDetails&type=Canned  file=rubrik_api.go line=51
panic: runtime error: index out of range

goroutine 12 [running]:
github.com/claranet/rubrik-exporter/rubrik.Rubrik.GetTaskDetails(0x7ffec760a687, 0x15, 0x7ffec760a6ae, 0xa, 0x7ffec760a6ca, 0xd, 0x0, 0x0, 0x1, 0x0)
	/opt/golang/projects/src/github.com/claranet/rubrik-exporter/rubrik/report.go:61 +0x5f4
main.(*RubrikStats).Collect(0xc42020e000, 0xc4200745a0)
	/opt/golang/projects/src/github.com/claranet/rubrik-exporter/export_rubrik.go:100 +0x2ba
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/opt/golang/projects/src/github.com/prometheus/client_golang/prometheus/registry.go:428 +0x199
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/opt/golang/projects/src/github.com/prometheus/client_golang/prometheus/registry.go:520 +0xe90
```

**Comment by Boolman** [comment]
url shouldnt end with / so this is a non-error.
